### ISSUE TITLE
Question about the 3 minutes

### ISSUE THREAD

**Issue by Ganbin** [jlobue10/Chia_stuff#1]
Hi, Thank you for this nice tool you provide.

Why did you set the 3 minutes timer? I was wondering if you choose this duration because your plotting time was a little under 3 minutes.

If we plot in 4-5 minutes it would be quite inefficient to have a 3 timer minute and we should adapt it.

Maybe a small note about it in the readme (or in the comment in the file) could help other to understand that value.

**Comment by jlobue10** [comment]
You make some good points. I'll update the README when I get a chance. In the meantime, I changed the timer to once every minute. This is in addition to script improvements that check whether a plot is already being made (and exits immediately if that's the case), and checks the free space available in the staging drive in order to make as many new plots as necessary to fill.

I found these changes to the script were necessary once I had Plow copying to multiple destinations in parallel.
